environment:
  global:
  # TODO This is the Rust channel that build jobs will use by default but can be
  # overridden on a case by case basis down below
    RUST_VERSION: stable

    CRATE_NAME: rust-csv

  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  matrix:
    # MinGW
    - TARGET: i686-pc-windows-gnu
    - TARGET: x86_64-pc-windows-gnu

    # MSVC
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: >-
      If ($env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($env:TARGET -eq 'i686-pc-windows-gnu') {
        $env:PATH += ';C:\msys64\mingw32\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build_script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source $HOME/.cargo/env
  - cargo build --release --bin cli

artifacts:
  - path: target/%TARGET%/release/cli.exe
    name: cli-%TARGET%.exe
  - path: target/release/cli
    name: cli-%TARGET%.exe

deploy:
  provider: GitHub
  artifact: cli-%TARGET%.exe, cli-%TARGET%
  auth_token:
    secure: RwzqvhGNJJ8/bUJ2xh93kmtR0EunmwViXIbjs/WaZKm4GEu0FmE4CzXeZ4dQtZTz
  draft: true
  prerelease: false
  on:
    branch: main
    event: push
    tags: true
