name: Rust_Build_Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Rust Project
      run: cargo build --verbose
    - name: Run Cargo tests
      run: cargo test --verbose
